/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author cass
 */
import javax.swing.JOptionPane;

public class Formulario extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Formulario.class.getName());
    private Datos d;
    private Procesos p;
    
    /**
     * Creates new form Formulario
     */
    public Formulario() {
        d = new Datos();
        p = new Procesos();
        initComponents();
        setLocationRelativeTo(null);
    }

    private void capturarDatos() {
        d.setDias(Integer.parseInt(txtDias.getText()));
        d.setPrecioPorDia(Double.parseDouble(txtPrecio.getText()));
        d.setTipoCliente((String) cmbTipoCliente.getSelectedItem());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPrecio = new javax.swing.JLabel();
        lblTitulo1 = new javax.swing.JLabel();
        lblCliente = new javax.swing.JLabel();
        lblDias = new javax.swing.JLabel();
        txtDias = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        cmbTipoCliente = new javax.swing.JComboBox<>();
        btnCalcular = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblPrecio.setFont(new java.awt.Font("JetBrainsMono NF", 1, 12)); // NOI18N
        lblPrecio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblPrecio.setText("Precio por día ($):");

        lblTitulo1.setFont(new java.awt.Font("JetBrainsMono NF", 1, 18)); // NOI18N
        lblTitulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo1.setText("SISTEMA DE ALQUIER VEHÍCULOS");

        lblCliente.setFont(new java.awt.Font("JetBrainsMono NF", 1, 12)); // NOI18N
        lblCliente.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCliente.setText("Tipo de cliente:");

        lblDias.setFont(new java.awt.Font("JetBrainsMono NF", 1, 12)); // NOI18N
        lblDias.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDias.setText("Cantidad de días:");

        txtDias.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        txtDias.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtPrecio.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        txtPrecio.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        cmbTipoCliente.setFont(new java.awt.Font("JetBrainsMono NF", 0, 12)); // NOI18N
        cmbTipoCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Regular", "Preferencial" }));

        btnCalcular.setFont(new java.awt.Font("JetBrainsMono NF", 1, 12)); // NOI18N
        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(this::btnCalcularActionPerformed);

        btnLimpiar.setFont(new java.awt.Font("JetBrainsMono NF", 1, 12)); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(this::btnLimpiarActionPerformed);

        btnSalir.setFont(new java.awt.Font("JetBrainsMono NF", 1, 12)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(this::btnSalirActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCalcular)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimpiar)
                        .addGap(18, 18, 18)
                        .addComponent(btnSalir))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblDias, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtDias))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(cmbTipoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtPrecio))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo1, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lblTitulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDias, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbTipoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalcular)
                    .addComponent(btnLimpiar)
                    .addComponent(btnSalir))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        // TODO add your handling code here:
        try {
            // Validar campos vacíos
            if (txtDias.getText().trim().isEmpty() || txtPrecio.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this,
                        "Por favor, complete todos los campos.",
                        "Campos incompletos",
                        JOptionPane.WARNING_MESSAGE);
                return;
            }

            capturarDatos();
            p.calcular(d);

            // Mostrar resultados en un cuadro de diálogo
            String mensaje = "=== RESUMEN DE ALQUILER ===\n"
                    + "Cantidad de días: " + d.getDias() + "\n"
                    + "Precio por día: $" + String.format("%.2f", d.getPrecioPorDia()) + "\n"
                    + "Tipo de cliente: " + d.getTipoCliente() + "\n"
                    + "----------------------------------------\n"
                    + "Costo Base: $" + String.format("%.2f", d.getCostoBase()) + "\n"
                    + "Cargo Seguro: "
                    + (d.getCostoBase() <= 300 ? "10%" : "7%")
                    + " → $" + String.format("%.2f", d.getCargoSeguro()) + "\n"
                    + "Subtotal: $" + String.format("%.2f", d.getSubtotal()) + "\n"
                    + "Descuento: "
                    + (d.getTipoCliente().equalsIgnoreCase("Regular") ? "4%" : "8%")
                    + " → $" + String.format("%.2f", d.getDescuento()) + "\n"
                    + "----------------------------------------\n"
                    + "TOTAL A PAGAR: $" + String.format("%.2f", d.getTotalPagar());

            JOptionPane.showMessageDialog(this, mensaje, "Factura de Alquiler", JOptionPane.INFORMATION_MESSAGE);

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                    "Error: Ingrese valores numéricos válidos.\nEjemplo: 5 para días, 50.00 para precio",
                    "Error de datos",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        txtDias.setText("");
        txtPrecio.setText("");
        cmbTipoCliente.setSelectedIndex(0);
        txtDias.requestFocus();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

        public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Formulario().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cmbTipoCliente;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblDias;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblTitulo1;
    private javax.swing.JTextField txtDias;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
